### PR TITLE
expose t0 as a mutable parameter

### PR DESCRIPTION
**Pull request by hellkite500**
Add t0 parameter to support calibration efforts

## Additions

- t0 parameter

## Testing

1. heavily exercised via calibration runs

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [x] Linux
- [x] MacOS

### CODE REVIEW

**Comment by SnowHydrology** [comment]
@hellkite500, this looks like a straightforward addition to TOPMODEL, but I want to make sure we've correctly identified `t0` first. All of the literature I can find identifies T<sub>0</sub> (how it's written in text) as the "transmissivity at saturation" with units of `m<sup>2</sup> h<sup>-1</sup>`. The [original Fortran code](https://github.com/NOAA-OWP/topmodel/tree/master/refs/original_code_fortran) does not provide any information on `t0`, while the [C adaptation](https://github.com/NOAA-OWP/topmodel/tree/master/refs/original_code_c) calls it "the areal average of ln(a/tanB)", i.e., the areal average of the TWI values. My reading and understanding is now that the comment in the C code is incorrect as it would make `t0` a fixed parameter for a given basin with different units than those typically presented in the literature. 

@lcunha0118 and @xfeng2021, what is your read on this?

**Comment by madMatchstick** [comment]
> @hellkite500, this looks like a straightforward addition to TOPMODEL, but I want to make sure we've correctly identified `t0` first. All of the literature I can find identifies T0 (how it's written in text) as the "transmissivity at saturation" with units of m2 h-1. The [original Fortran code](https://github.com/NOAA-OWP/topmodel/tree/master/refs/original_code_fortran) does not provide any information on `t0`, while the [C adaptation](https://github.com/NOAA-OWP/topmodel/tree/master/refs/original_code_c) calls it "the areal average of ln(a/tanB)", i.e., the areal average of the TWI values. My reading and understanding is now that the comment in the C code is incorrect as it would make `t0` a fixed parameter for a given basin with different units than those typically presented in the literature.
> 
> @lcunha0118 and @xfeng2021, what is your read on this?

Just thought I'd quickly chime in here; or more so save a few of you some searching as I have zero insights in light of hydrology terms...
Agree with @SnowHydrology, this is a simple/direct PR. The only comment regarding `t0` in [TMOD9502.f](https://github.com/NOAA-OWP/topmodel/blob/e179edd558b1ff32216b2b25514d3423e3a50c50/refs/original_code_fortran/TMOD9502.f#L487) is,
```
*  Convert parameters to m/time step DT
*  with exception of XK0 which must stay in m/h
*                    Q0 is already in m/time step
*                    T0 is input as Ln(To)
```

And in [tmod9502.c](https://github.com/NOAA-OWP/topmodel/blob/e179edd558b1ff32216b2b25514d3423e3a50c50/refs/original_code_c/tmod9502.c#L178),
```
/* model parameters and input scalars */
double szm;   /* this is the famous m parameter */
double t0;    /* this is the areal average of ln(a/tanB)  */
```

And lastly, in the Hess 2020 paper [History of Topmodel, Table 1](https://hess.copernicus.org/preprints/hess-2020-409/hess-2020-409.pdf) at ln 165:
 ```
t0 is the downslope transmissivity when the soil is just saturated
```

So in sum, and again, I agree with @SnowHydrology  and that we should simply update the definition in both (commented) code and documentation.

**Comment by xfeng2021** [comment]
T0 in Fortran and C versions of TOPMODEL is the same. The variable SZQ, equals to T0 Δt exp(-λ), is the discharge when the catchment is saturated. T0 is the transmissivity of the soil in the saturated state and  λ is the topographic index according to the definitions in the literature. SZQ is calculated as EXP(T0DT-TL) in the Fortran code. This term is used for the calculation of baseflow, expressed as QB=SZQ*EXP(-SBAR/SZM) in the code.

You can verify this further.

**Comment by madMatchstick** [comment]
> T0 in Fortran and C versions of TOPMODEL is the same. The variable SZQ, equals to T0 Δt exp(-λ), is the discharge when the catchment is saturated. T0 is the transmissivity of the soil in the saturated state and λ is the topographic index according to the definitions in the literature. SZQ is calculated as EXP(T0DT-TL) in the Fortran code. This term is used for the calculation of baseflow, expressed as QB=SZQ*EXP(-SBAR/SZM) in the code.
> 
> You can verify this further.

@xfeng2021 Can you please confirm correct units for `t0` in this table [here](https://github.com/hellkite500/topmodel/blob/master/docs/INPUT_FILES_EXPLAINED.md#parameter-data)? Thanks!

**Comment by lcunha0118** [comment]
Sorry I missed this thread! I agree with @xfeng2021 and the units should be meter/hour.

**Review by madMatchstick — APPROVED** [review]
Description of variable `t0` updated in docs/etc.

**Pull request merged**
